#!/usr/bin/env python3
"""Generate lightweight repository source and process documentation."""

from __future__ import annotations

import argparse
import difflib
import json
import re
import sys
from collections import Counter
from pathlib import Path


ROOT = Path(__file__).resolve().parents[2]
OUT_DIR = ROOT / "docs" / "generated"

SWIFT_TYPE_RE = re.compile(r"^\s*(?:@\w+\s+)*(?:public|private|internal|fileprivate|open)?\s*(?:final\s+)?(class|struct|enum|actor|protocol)\s+([A-Za-z_][A-Za-z0-9_]*)", re.MULTILINE)
PY_DEF_RE = re.compile(r"^\s*(class|def)\s+([A-Za-z_][A-Za-z0-9_]*)", re.MULTILINE)


def rel(path: Path) -> str:
    return str(path.relative_to(ROOT))


def read_text(path: Path) -> str:
    return path.read_text(encoding="utf-8", errors="replace")


def swift_types(path: Path) -> list[str]:
    return [f"{kind} {name}" for kind, name in SWIFT_TYPE_RE.findall(read_text(path))]


def python_defs(path: Path) -> list[str]:
    return [f"{kind} {name}" for kind, name in PY_DEF_RE.findall(read_text(path))]


def table(headers: list[str], rows: list[list[str]]) -> list[str]:
    lines = [
        "| " + " | ".join(headers) + " |",
        "| " + " | ".join("---" for _ in headers) + " |",
    ]
    lines.extend("| " + " | ".join(cell.replace("|", "\\|") for cell in row) + " |" for row in rows)
    return lines


def source_map() -> str:
    swift_files = sorted((ROOT / "Upmarket" / "Upmarket").rglob("*.swift"))
    python_files = sorted((ROOT / "UpmarketPython").rglob("*.py"))
    test_files = sorted((ROOT / "Upmarket").glob("Upmarket*Tests/**/*.swift"))
    docs = sorted((ROOT / "docs").rglob("*.md"))

    section_rows = [
        ["Swift app", "`Upmarket/Upmarket`", f"{len(swift_files)} Swift files", "App shell, UI, domain models, services, StoreKit, native extraction"],
        ["Python bridge", "`UpmarketPython`", f"{len(python_files)} Python files", "Conversion/model helper code copied into the packaged Python runtime"],
        ["Tests", "`Upmarket/UpmarketTests`, `Upmarket/UpmarketUITests`", f"{len(test_files)} Swift test files", "Unit and UI validation"],
        ["Scripts", "`scripts`", f"{len(list((ROOT / 'scripts').rglob('*')))} entries", "Release, corpus, CI, dependency, and documentation automation"],
        ["Docs", "`docs`", f"{len(docs)} Markdown files", "Plans, release process, generated source maps, runbooks"],
    ]

    service_rows = []
    for path in sorted((ROOT / "Upmarket" / "Upmarket" / "Services").glob("*.swift")):
        service_rows.append([f"`{rel(path)}`", ", ".join(swift_types(path)) or "-"])

    domain_rows = []
    for path in sorted((ROOT / "Upmarket" / "Upmarket" / "Domain").glob("*.swift")):
        domain_rows.append([f"`{rel(path)}`", ", ".join(swift_types(path)) or "-"])

    python_rows = []
    for path in python_files:
        definitions = python_defs(path)
        python_rows.append([f"`{rel(path)}`", ", ".join(definitions[:8]) or "-"])

    lines = [
        "# Generated Source Map",
        "",
        "Generated by `scripts/docs/generate_repo_docs.py`. Do not edit by hand.",
        "",
        "## Repository Areas",
        "",
        *table(["Area", "Path", "Size", "Role"], section_rows),
        "",
        "## Domain Models",
        "",
        *table(["File", "Types"], domain_rows),
        "",
        "## Swift Services",
        "",
        *table(["File", "Types"], service_rows),
        "",
        "## Python Entry Points",
        "",
        *table(["File", "Definitions"], python_rows),
        "",
    ]
    return "\n".join(lines)


def conversion_flow() -> str:
    pathways = json.loads((ROOT / "docs" / "release" / "conversion_pathways.json").read_text(encoding="utf-8"))
    pathway_rows = []
    for name, config in sorted(pathways["pathways"].items()):
        pathway_rows.append([
            f"`{name}`",
            config.get("release_status", "-"),
            ", ".join(config.get("valid_categories", [])),
            config.get("runner", "-"),
            config.get("owner", "-"),
        ])

    lines = [
        "# Generated Conversion Flow",
        "",
        "Generated by `scripts/docs/generate_repo_docs.py`. Do not edit by hand.",
        "",
        "## Runtime Flow",
        "",
        "1. User action enters SwiftUI views or Quick Action handoff.",
        "2. `ConversionQueue` owns job state, entitlement-gated enqueue, retry, cancellation, progress, and result/error state.",
        "3. `ConversionRunner` copies the source into an app-owned workspace and chooses the concrete extraction path.",
        "4. Apple-native paths are attempted where valid: PDFKit, Vision, Speech, ImageIO, and AVFoundation.",
        "5. Python paths go through `PythonWorker`; views and queue code do not import or call Python directly.",
        "6. Post-processing refines Markdown through native language/writing adapters with graceful availability checks.",
        "",
        "## Conversion Pathway Registry",
        "",
        *table(["Pathway", "Status", "Valid Categories", "Runner", "Owner"], pathway_rows),
        "",
        "## Benchmark Outputs",
        "",
        "- Current tracked benchmark table: `docs/release/CORPUS_BENCHMARKS.md`",
        "- Pathway registry: `docs/release/conversion_pathways.json`",
        "- Baseline ledger: `docs/release/corpus_pathway_baseline.json`",
        "- Release candidate artifact: `corpus-pathway-comparison`",
        "",
    ]
    return "\n".join(lines)


def release_automation() -> str:
    workflow_rows = []
    for path in sorted((ROOT / ".github" / "workflows").glob("*.yml")):
        text = read_text(path)
        steps = re.findall(r"^\s+- name: (.+)$", text, flags=re.MULTILINE)
        workflow_rows.append([f"`{rel(path)}`", ", ".join(steps) or "-"])

    script_rows = []
    for path in sorted((ROOT / "scripts" / "ci").glob("*")):
        if path.is_file():
            first_line = read_text(path).splitlines()[0] if read_text(path).splitlines() else ""
            script_rows.append([f"`{rel(path)}`", first_line.replace("#!", "").strip() or "-"])

    lock_rows = []
    for lock in (ROOT / "requirements.txt", ROOT / "requirements-candidate.txt"):
        if lock.exists():
            packages = [
                line.split("==", 1)[0].strip()
                for line in read_text(lock).splitlines()
                if line.strip() and not line.startswith("#")
            ]
            lock_rows.append([f"`{rel(lock)}`", str(len(packages)), ", ".join(packages[:12])])

    lines = [
        "# Generated Release Automation Map",
        "",
        "Generated by `scripts/docs/generate_repo_docs.py`. Do not edit by hand.",
        "",
        "## GitHub Workflows",
        "",
        *table(["Workflow", "Named Steps"], workflow_rows),
        "",
        "## CI Scripts",
        "",
        *table(["Script", "Purpose Hint"], script_rows),
        "",
        "## Dependency Locks",
        "",
        *table(["Lock", "Packages", "Examples"], lock_rows),
        "",
    ]
    return "\n".join(lines)


def write_or_check(path: Path, content: str, check: bool) -> list[str]:
    content = content.rstrip() + "\n"
    if check:
        existing = path.read_text(encoding="utf-8") if path.exists() else ""
        if existing != content:
            diff = "\n".join(difflib.unified_diff(
                existing.splitlines(),
                content.splitlines(),
                fromfile=str(path),
                tofile=f"{path} (generated)",
                lineterm="",
            ))
            return [diff or f"{path} is stale"]
        return []
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8")
    return []


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true", help="fail if generated docs are stale")
    args = parser.parse_args()

    outputs = {
        OUT_DIR / "SOURCE_MAP.md": source_map(),
        OUT_DIR / "CONVERSION_FLOW.md": conversion_flow(),
        OUT_DIR / "RELEASE_AUTOMATION.md": release_automation(),
    }

    errors: list[str] = []
    for path, content in outputs.items():
        errors.extend(write_or_check(path, content, args.check))

    if errors:
        for error in errors:
            print(error, file=sys.stderr)
        print("error: generated repository docs are stale; run scripts/docs/generate_repo_docs.py", file=sys.stderr)
        return 1

    mode = "validated" if args.check else "generated"
    print(f"ok: {mode} {len(outputs)} repository documentation file(s)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
